services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./tmp:/app/tmp
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_PORT=8080
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT=/app/credentials/firebase-service-account.json
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
    restart: unless-stopped
    command: air -c .air.toml
